Chapter9-FoodPin
VivianaSara/FoodPin pull request #1
Opened 2022-04-12 07:16 UTC by VivianaSara

I started the FoodPin app and in this chapter I customed the prototype cell like this

it supposed to looks like
<img width="217" alt="Screenshot 2022-04-12 at 13 53 54" src="https://user-images.githubusercontent.com/103035689/162945029-a34c4b08-3ab5-489a-8d1f-788b8ae7b634.png">

and this is how it looks
<img width="429" alt="Screenshot 2022-04-12 at 13 58 04" src="https://user-images.githubusercontent.com/103035689/162945600-81324ac4-a55e-4f46-b9fe-ddcb694a6019.png">

I used a RestaurantTableViewController a subclass of TableViewController and RestaurantTableViewCell a subclass of TableViewCell.

RestaurantTableViewController contains a function configureDataSource where I custom every cell with an image and a name. 

RestaurantTableViewCell contains just the components of the cell (labels and thee image)

2022-04-12 13:40 UTC, ralumarusca requested changes

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +
there should be only 1 empty line

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +return cell  }
these lines should be aligned and the end bracket should be on the next line

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +
lines should be aligned and please remove the empty line

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +
too many empty lines

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViwCell.swift
> +    @IBOutlet var thumbnailImageView: UIImageView!
IBOutets should be private

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViwCell.swift
> +
unused methods can be removed

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableeViewCell.swift
> +class RestaurantTableeViewCell: UITableViewCell{
typo in the class name

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableeViewCell.swift
> +    @IBOutlet var thumbnailImageView: UIImageView!
IBOutlets should be private

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableeViewCell.swift
> +
unused methods can be removed

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableeViewCell.swift
> +        // #warning Incomplete implementation, return the number of sections
comment can be removed because there is an implementation

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableeViewCell.swift
> +        // #warning Incomplete implementation, return the number of rows
comment can be removed because there is an implementation

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableeViewCell.swift
> +    /*
Commented methods can be removed if you don't need them in the future

2022-04-12 13:40 UTC, ralumarusca commented on FoodPin/FoodPin/ViewController.swift
> +}
file can be removed if it's not used

2022-04-14 06:49 UTC, ralumarusca requested changes

2022-04-14 06:49 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewCell.swift
> +    @IBOutlet var thumbnailImageView: UIImageView!
These should be private, like this:
@IBOutlet private var nameLabel: UILabel!
And you can create a public method, like "configureCell" to be able to modify these properties from the viewController

2022-04-14 06:49 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +            return cell  }
closing bracket can be on the next line

2022-04-14 06:49 UTC, ralumarusca commented on FoodPin/FoodPin/RestaurantTableViewController.swift
> +            dataSource.apply(snapshot, animatingDifferences: false)
lines should be aligned to the left, under "var"

2022-04-14 09:08 UTC, czegreanu commented on FoodPin/FoodPin/SceneDelegate.swift
> +    }
these methods can be deleted, not used

2022-04-14 11:33 UTC, madalinaCojocaru1 approved these changes

2022-04-14 12:00 UTC, paulpop10 approved these changes

2022-04-14 12:29 UTC, merged