Chapter 12: Table Row Deletion, Swipe for Actions, Activity Controller and MVC + challenge
VivianaSara/FoodPin pull request #6
Opened 2022-04-20 12:31 UTC by VivianaSara

###  Changes in code
- in RestaurantTableViewController class I added 2 override functions for swipe-to-left ( includes: delete and share action) & swipe-to-right ( include: mark as favorite action)
- created a new Model class RestaurantDiffableDataSource for activate the swipe action

### UI Updates

- **Delete&Share** 

> swipe-to-left
<img width="371" alt="Screenshot 2022-04-20 at 15 17 35" src="https://user-images.githubusercontent.com/103035689/164228818-7353dcf6-80da-4419-8b17-2bccb5eac7f4.png">

> after deletion app will looks like ( the cell above is deleted  )

<img width="371" alt="Screenshot 2022-04-20 at 15 18 18" src="https://user-images.githubusercontent.com/103035689/164229019-fcc564ca-ea99-4cca-8db1-ca26053e192c.png">

> share action looks like
<img width="371" alt="Screenshot 2022-04-20 at 15 18 34" src="https://user-images.githubusercontent.com/103035689/164229763-1a12a04f-24ff-45b9-8b48-c6cbc8ae5399.png">

###  
**    **
- **Mark as favorite**
> swipe-to-right
<img width="371" alt="Screenshot 2022-04-20 at 15 17 42" src="https://user-images.githubusercontent.com/103035689/164229359-cd6beb01-2637-4f34-9d00-bd509dec52ed.png">

> after this action the cell will looks like
<img width="371" alt="Screenshot 2022-04-20 at 15 18 07" src="https://user-images.githubusercontent.com/103035689/164229477-a7fca5b3-f28c-42a1-a867-5cf1f93ce729.png">

> remove from favorite 

<img width="371" alt="Screenshot 2022-04-20 at 15 18 02" src="https://user-images.githubusercontent.com/103035689/164229518-f6e924b6-017b-41db-aae8-e970deff963f.png">

2022-04-20 14:42 UTC, ralumarusca requested changes

2022-04-20 14:42 UTC, ralumarusca commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +            else {
For guard statement **else** is usually on the same line with **guard**

2022-04-20 14:42 UTC, ralumarusca commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +            return UISwipeActionsConfiguration()
here you can also return nil, because the return type of the method is optional

2022-04-21 08:38 UTC, paulpop10 commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +        // Share action
empty space needed

2022-04-21 08:39 UTC, paulpop10 commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
> +            cell.setHeartImage(isFavorite: self.restaurants[indexPath.row].getIsFavorite())
empty space needed

2022-04-21 09:19 UTC, paulpop10 commented on FoodPin/FoodPin/Controller/RestaurantTableViewController.swift
>                  cell.configureCell(nameLabel: restaurant.getName(), locationLabel: restaurant.getLocation(),
this block needs to be aligned with the rest of the method body

2022-04-26 06:25 UTC, ralumarusca approved these changes

2022-04-26 07:28 UTC, paulpop10 approved these changes

2022-04-26 07:44 UTC, merged